// Auto-generated chain rules — DO NOT EDIT
// Generated from pharmacopia.json by generate_chain_rules.zig
//
// To regenerate: zig build chain-rules

const std = @import("std");

pub const ChainRule = struct {
    opcode: u8,
    name: []const u8,
    pre_state: []const []const u8,
    post_state: []const []const u8,
    side_effects: []const []const u8,
    suggests_after: []const []const u8,
    warns_if_before: []const []const u8,
    safety_level: u8,
};

pub const chain_rules: [40]ChainRule = .{
    .{
        .opcode = 0x01,
        .name = "CLAIM",
        .safety_level = 3,
        .pre_state = &.{},
        .post_state = &.{"vessel_claimed"},
        .side_effects = &.{"driver_unbound"},
        .suggests_after = &.{"LIMIT", "STAKE"},
        .warns_if_before = &.{"BIND"},
    },
    .{
        .opcode = 0x02,
        .name = "STAKE",
        .safety_level = 2,
        .pre_state = &.{},
        .post_state = &.{"memory_reserved"},
        .side_effects = &.{"memory_allocated"},
        .suggests_after = &.{"FLOW", "SLICE"},
        .warns_if_before = &.{},
    },
    .{
        .opcode = 0x03,
        .name = "FLOW",
        .safety_level = 4,
        .pre_state = &.{"vessel_claimed", "aperture_mapped"},
        .post_state = &.{"data_transferred", "operation_pending"},
        .side_effects = &.{"thermal_increase", "memory_modified"},
        .suggests_after = &.{"SYNC", "FENCE"},
        .warns_if_before = &.{},
    },
    .{
        .opcode = 0x04,
        .name = "SHIFT",
        .safety_level = 4,
        .pre_state = &.{"vessel_claimed"},
        .post_state = &.{"aperture_mapped"},
        .side_effects = &.{"memory_remapped"},
        .suggests_after = &.{"FLOW", "SLICE"},
        .warns_if_before = &.{},
    },
    .{
        .opcode = 0x05,
        .name = "FENCE",
        .safety_level = 4,
        .pre_state = &.{},
        .post_state = &.{"condition_met"},
        .side_effects = &.{},
        .suggests_after = &.{"SIGNAL", "SYNC"},
        .warns_if_before = &.{},
    },
    .{
        .opcode = 0x06,
        .name = "SYNC",
        .safety_level = 2,
        .pre_state = &.{},
        .post_state = &.{"memory_visible"},
        .side_effects = &.{},
        .suggests_after = &.{"FENCE", "SIGNAL"},
        .warns_if_before = &.{},
    },
    .{
        .opcode = 0x09,
        .name = "SIGNAL",
        .safety_level = 4,
        .pre_state = &.{},
        .post_state = &.{"event_triggered"},
        .side_effects = &.{"interrupt_sent"},
        .suggests_after = &.{"AUDIT", "WATCH"},
        .warns_if_before = &.{},
    },
    .{
        .opcode = 0x0A,
        .name = "YIELD",
        .safety_level = 1,
        .pre_state = &.{},
        .post_state = &.{},
        .side_effects = &.{"time_elapsed"},
        .suggests_after = &.{},
        .warns_if_before = &.{},
    },
    .{
        .opcode = 0x0E,
        .name = "LIMIT",
        .safety_level = 3,
        .pre_state = &.{"vessel_claimed"},
        .post_state = &.{"constraint_set"},
        .side_effects = &.{},
        .suggests_after = &.{"FLOW", "SLICE", "POKE"},
        .warns_if_before = &.{},
    },
    .{
        .opcode = 0x3B,
        .name = "SLICE",
        .safety_level = 4,
        .pre_state = &.{"vessel_claimed", "aperture_mapped"},
        .post_state = &.{"data_chunked", "operation_pending"},
        .side_effects = &.{"thermal_increase", "memory_modified"},
        .suggests_after = &.{"SYNC", "FENCE"},
        .warns_if_before = &.{},
    },
    .{
        .opcode = 0x3C,
        .name = "PIPE",
        .safety_level = 3,
        .pre_state = &.{"vessel_claimed"},
        .post_state = &.{"pipe_established"},
        .side_effects = &.{"dma_engine_active"},
        .suggests_after = &.{"WATCH", "GUARD"},
        .warns_if_before = &.{},
    },
    .{
        .opcode = 0x11,
        .name = "RHYTHM",
        .safety_level = 2,
        .pre_state = &.{"vessel_claimed"},
        .post_state = &.{"timing_set"},
        .side_effects = &.{},
        .suggests_after = &.{},
        .warns_if_before = &.{},
    },
    .{
        .opcode = 0x17,
        .name = "ECHO",
        .safety_level = 1,
        .pre_state = &.{},
        .post_state = &.{},
        .side_effects = &.{},
        .suggests_after = &.{},
        .warns_if_before = &.{},
    },
    .{
        .opcode = 0x18,
        .name = "STASIS",
        .safety_level = 3,
        .pre_state = &.{"vessel_claimed"},
        .post_state = &.{"bus_locked"},
        .side_effects = &.{"traffic_frozen"},
        .suggests_after = &.{"FLOW", "SLICE"},
        .warns_if_before = &.{},
    },
    .{
        .opcode = 0x2A,
        .name = "FLUX",
        .safety_level = 2,
        .pre_state = &.{},
        .post_state = &.{"cache_invalidated"},
        .side_effects = &.{},
        .suggests_after = &.{"FLOW", "AUDIT"},
        .warns_if_before = &.{},
    },
    .{
        .opcode = 0x2B,
        .name = "AUDIT",
        .safety_level = 2,
        .pre_state = &.{},
        .post_state = &.{"residue_checked"},
        .side_effects = &.{},
        .suggests_after = &.{},
        .warns_if_before = &.{},
    },
    .{
        .opcode = 0x2C,
        .name = "DRY_RUN",
        .safety_level = 1,
        .pre_state = &.{},
        .post_state = &.{},
        .side_effects = &.{},
        .suggests_after = &.{},
        .warns_if_before = &.{},
    },
    .{
        .opcode = 0x2D,
        .name = "MOCK",
        .safety_level = 1,
        .pre_state = &.{},
        .post_state = &.{},
        .side_effects = &.{},
        .suggests_after = &.{},
        .warns_if_before = &.{},
    },
    .{
        .opcode = 0x2E,
        .name = "PROVE",
        .safety_level = 1,
        .pre_state = &.{},
        .post_state = &.{},
        .side_effects = &.{},
        .suggests_after = &.{},
        .warns_if_before = &.{},
    },
    .{
        .opcode = 0x2F,
        .name = "WATCH",
        .safety_level = 1,
        .pre_state = &.{},
        .post_state = &.{},
        .side_effects = &.{},
        .suggests_after = &.{},
        .warns_if_before = &.{},
    },
    .{
        .opcode = 0x30,
        .name = "TRACE",
        .safety_level = 1,
        .pre_state = &.{},
        .post_state = &.{},
        .side_effects = &.{},
        .suggests_after = &.{},
        .warns_if_before = &.{},
    },
    .{
        .opcode = 0x31,
        .name = "GUARD",
        .safety_level = 3,
        .pre_state = &.{},
        .post_state = &.{"guard_armed"},
        .side_effects = &.{},
        .suggests_after = &.{},
        .warns_if_before = &.{},
    },
    .{
        .opcode = 0x32,
        .name = "ISOLATE",
        .safety_level = 4,
        .pre_state = &.{"vessel_claimed"},
        .post_state = &.{"isolated"},
        .side_effects = &.{"os_access_revoked"},
        .suggests_after = &.{"FLOW", "POKE"},
        .warns_if_before = &.{},
    },
    .{
        .opcode = 0x33,
        .name = "VERIFY",
        .safety_level = 3,
        .pre_state = &.{},
        .post_state = &.{"state_verified"},
        .side_effects = &.{},
        .suggests_after = &.{},
        .warns_if_before = &.{},
    },
    .{
        .opcode = 0x34,
        .name = "AFFINITY",
        .safety_level = 3,
        .pre_state = &.{"vessel_claimed"},
        .post_state = &.{"resource_pinned"},
        .side_effects = &.{"scheduler_bypassed"},
        .suggests_after = &.{},
        .warns_if_before = &.{},
    },
    .{
        .opcode = 0x35,
        .name = "TUNNEL",
        .safety_level = 3,
        .pre_state = &.{"vessel_claimed", "vessel_claimed"},
        .post_state = &.{"tunnel_established"},
        .side_effects = &.{"iommu_bypassed"},
        .suggests_after = &.{"FLOW", "SLICE"},
        .warns_if_before = &.{},
    },
    .{
        .opcode = 0x36,
        .name = "SUSPEND",
        .safety_level = 3,
        .pre_state = &.{"vessel_claimed"},
        .post_state = &.{"subsystem_suspended"},
        .side_effects = &.{"auto_behavior_paused"},
        .suggests_after = &.{"FLOW", "POKE"},
        .warns_if_before = &.{},
    },
    .{
        .opcode = 0x37,
        .name = "COORDINATE",
        .safety_level = 2,
        .pre_state = &.{"vessel_claimed", "vessel_claimed"},
        .post_state = &.{"devices_coordinated"},
        .side_effects = &.{"state_synchronized"},
        .suggests_after = &.{"FLOW", "SLICE"},
        .warns_if_before = &.{},
    },
    .{
        .opcode = 0x39,
        .name = "DIRECT",
        .safety_level = 4,
        .pre_state = &.{"vessel_claimed"},
        .post_state = &.{"controller_access"},
        .side_effects = &.{"os_bypassed"},
        .suggests_after = &.{"FLOW", "POKE"},
        .warns_if_before = &.{},
    },
    .{
        .opcode = 0x3A,
        .name = "BIND",
        .safety_level = 4,
        .pre_state = &.{},
        .post_state = &.{"device_bound", "vessel_claimed"},
        .side_effects = &.{"os_access_revoked"},
        .suggests_after = &.{"SHIFT", "LIMIT", "PIPE"},
        .warns_if_before = &.{},
    },
    .{
        .opcode = 0x1B,
        .name = "PERSIST",
        .safety_level = 3,
        .pre_state = &.{"vessel_claimed"},
        .post_state = &.{"data_persisted"},
        .side_effects = &.{"memory_pinned"},
        .suggests_after = &.{"VERIFY"},
        .warns_if_before = &.{},
    },
    .{
        .opcode = 0x1C,
        .name = "POKE",
        .safety_level = 5,
        .pre_state = &.{"vessel_claimed"},
        .post_state = &.{"bits_modified"},
        .side_effects = &.{"thermal_increase", "memory_modified", "potential_data_corruption"},
        .suggests_after = &.{"AUDIT", "FLUX"},
        .warns_if_before = &.{},
    },
    .{
        .opcode = 0x1D,
        .name = "RESET",
        .safety_level = 4,
        .pre_state = &.{"vessel_claimed"},
        .post_state = &.{"subsystem_reset"},
        .side_effects = &.{"power_state_changed"},
        .suggests_after = &.{"REVERT", "CLAIM"},
        .warns_if_before = &.{},
    },
    .{
        .opcode = 0x1E,
        .name = "INJECT",
        .safety_level = 4,
        .pre_state = &.{"vessel_claimed"},
        .post_state = &.{"firmware_loaded"},
        .side_effects = &.{"device_reconfigured"},
        .suggests_after = &.{"VERIFY", "REVERT"},
        .warns_if_before = &.{},
    },
    .{
        .opcode = 0x1F,
        .name = "WIPE",
        .safety_level = 5,
        .pre_state = &.{"vessel_claimed"},
        .post_state = &.{"data_erased"},
        .side_effects = &.{"memory_zeroed"},
        .suggests_after = &.{"AUDIT", "VERIFY"},
        .warns_if_before = &.{},
    },
    .{
        .opcode = 0x07,
        .name = "SENSE",
        .safety_level = 1,
        .pre_state = &.{},
        .post_state = &.{"sensor_read"},
        .side_effects = &.{},
        .suggests_after = &.{"GUARD", "LIMIT"},
        .warns_if_before = &.{},
    },
    .{
        .opcode = 0x08,
        .name = "PULSE",
        .safety_level = 2,
        .pre_state = &.{},
        .post_state = &.{"signal_emitted"},
        .side_effects = &.{},
        .suggests_after = &.{},
        .warns_if_before = &.{},
    },
    .{
        .opcode = 0x0B,
        .name = "RECAST",
        .safety_level = 3,
        .pre_state = &.{"vessel_claimed"},
        .post_state = &.{"device_reconfigured"},
        .side_effects = &.{"state_changed"},
        .suggests_after = &.{"VERIFY"},
        .warns_if_before = &.{},
    },
    .{
        .opcode = 0x0C,
        .name = "SNAP",
        .safety_level = 2,
        .pre_state = &.{"vessel_claimed"},
        .post_state = &.{"state_serialized"},
        .side_effects = &.{},
        .suggests_after = &.{"REVERT"},
        .warns_if_before = &.{},
    },
    .{
        .opcode = 0x0D,
        .name = "REVERT",
        .safety_level = 2,
        .pre_state = &.{"state_serialized"},
        .post_state = &.{"state_restored"},
        .side_effects = &.{"memory_restored"},
        .suggests_after = &.{"VERIFY", "AUDIT"},
        .warns_if_before = &.{},
    },
};

pub const chain_rule_count: usize = 40;

pub fn getChainRule(opcode: u8) ?*const ChainRule {
    for (&chain_rules) |*rule| {
        if (rule.opcode == opcode) return rule;
    }
    return null;
}
