// Copyright 2026 Randy Smits-Schreuder Goedheijt
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Runtime Exception for Use as a Language:
// When the Work or any Derivative Work thereof is used to generate code
// ("generated code"), such generated code shall not be subject to the
// terms of this License, provided that the generated code itself is not
// a Derivative Work of the Work. This exception does not apply to code
// that is itself a compiler, interpreter, or similar tool that incorporates
// or embeds the Work.

// Pharmacopia module — tool registry generated from pharmacopia.json
//
// The dispatch table is auto-generated by: zig build dispatch
// To add a tool: edit pharmacopia.json, then regenerate.
//
// Tools can be written in any language (Zig, SPARK Ada, C, Rust) as long as
// they provide a Zig wrapper implementing the ToolInterface contract.

pub const dispatch = @import("dispatch_table.zig");
pub const interface = @import("interface.zig");

pub const Tool = dispatch.Tool;
pub const getTool = dispatch.getTool;
pub const all_tools = dispatch.all_tools;
pub const tool_count = dispatch.tool_count;

// Re-export tool modules for direct access
pub const claim = @import("core/claim.zig");
pub const flow = @import("core/spark_flow.zig");
pub const shift = @import("core/spark_shift.zig");
pub const fence = @import("core/spark_fence.zig");
pub const sync = @import("core/sync.zig");
pub const signal = @import("core/spark_signal.zig");
pub const yield_tool = @import("core/yield.zig");
pub const veil = @import("core/veil.zig");
pub const snap = @import("core/snap.zig");
pub const revert = @import("core/revert.zig");
pub const stake = @import("core/stake.zig");
pub const echo = @import("core/echo.zig");
pub const limit = @import("core/limit.zig");
pub const refract = @import("core/spark_refract.zig");
pub const pipe = @import("core/pipe.zig");
pub const substrate = @import("substrate/");
pub const ossify = @import("substrate/ossify.zig");
pub const bond = @import("substrate/bond.zig");
pub const still = @import("substrate/still.zig");
pub const resonate = @import("substrate/resonate.zig");
pub const oscillate = @import("substrate/oscillate.zig");
pub const imc_hijack = @import("substrate/imc_hijack.zig");
pub const occupy = @import("substrate/occupy.zig");
pub const strike = @import("substrate/strike.zig");
pub const forging = @import("forging/");
pub const void_tool = @import("forging/void.zig");
pub const recast = @import("forging/recast.zig");
pub const forge_tool = @import("forging/forge.zig");
pub const pulse_mod = @import("pulse/pulse.zig");
pub const sense = @import("pulse/sense.zig");
pub const stasis = @import("pulse/stasis.zig");
pub const rhythm = @import("pulse/rhythm.zig");
pub const flux = @import("transmutation/flux.zig");
pub const guard = @import("safety/guard.zig");
pub const audit = @import("testing/audit.zig");
pub const dry_run = @import("testing/dry_run.zig");
pub const mock = @import("testing/mock.zig");
pub const prove = @import("testing/prove.zig");
pub const molt = @import("solidification/molt.zig");
pub const fossilize = @import("solidification/fossilize.zig");
pub const quench = @import("calcination/quench.zig");
pub const isolate = @import("safety/isolate.zig");
pub const verify = @import("safety/verify.zig");
pub const watch = @import("monitoring/watch.zig");
pub const trace = @import("monitoring/trace.zig");
