// Pharmacopia module — tool registry generated from pharmacopia.json
//
// The dispatch table is auto-generated by: zig build dispatch
// To add a tool: edit pharmacopia.json, then regenerate.
//
// Tools can be written in any language (SPARK, Zig, C, ASM) as long as
// they provide a Zig wrapper implementing the ToolInterface contract.

pub const dispatch = @import("dispatch_table.zig");
pub const interface = @import("interface.zig");

pub const Tool = dispatch.Tool;
pub const getTool = dispatch.getTool;
pub const all_tools = dispatch.all_tools;
pub const tool_count = dispatch.tool_count;

// Re-export tool modules for direct access
pub const claim = @import("core/claim.zig");
pub const flow = @import("core/spark_flow.zig");
pub const shift = @import("core/spark_shift.zig");
pub const fence = @import("core/spark_fence.zig");
pub const sync = @import("core/sync.zig");
pub const signal = @import("core/spark_signal.zig");
pub const yield_tool = @import("core/yield.zig");
pub const snap = @import("core/snap.zig");
pub const revert = @import("core/revert.zig");
pub const stake = @import("core/stake.zig");
pub const echo = @import("core/echo.zig");
pub const limit = @import("core/limit.zig");
pub const slice = @import("core/spark_slice.zig");
pub const pipe = @import("core/pipe.zig");
pub const poke = @import("substrate/poke.zig");
pub const direct = @import("substrate/direct.zig");
pub const bind = @import("substrate/bind.zig");
pub const affinity = @import("substrate/affinity.zig");
pub const tunnel = @import("substrate/tunnel.zig");
pub const suspend_tool = @import("substrate/suspend.zig");
pub const coordinate = @import("substrate/coordinate.zig");
pub const forging = @import("forging/");
pub const inject_tool = @import("forging/inject.zig");
pub const recast = @import("forging/recast.zig");
pub const wipe = @import("forging/wipe.zig");
pub const pulse_mod = @import("pulse/pulse.zig");
pub const sense = @import("pulse/sense.zig");
pub const stasis = @import("pulse/stasis.zig");
pub const rhythm = @import("pulse/rhythm.zig");
pub const flux = @import("transmutation/flux.zig");
pub const guard = @import("safety/guard.zig");
pub const audit = @import("testing/audit.zig");
pub const dry_run = @import("testing/dry_run.zig");
pub const mock = @import("testing/mock.zig");
pub const prove = @import("testing/prove.zig");
pub const persist = @import("solidification/persist.zig");
pub const reset_tool = @import("calcination/reset.zig");
pub const isolate = @import("safety/isolate.zig");
pub const verify = @import("safety/verify.zig");
pub const watch = @import("monitoring/watch.zig");
pub const trace = @import("monitoring/trace.zig");

// Merged tools (kept as aliases for v4 compatibility during transition)
pub const refract = slice;       // REFRACT → SLICE
pub const strike = poke;         // STRIKE → POKE
pub const imc_hijack = direct;   // IMC_HIJACK → DIRECT
pub const occupy = bind;         // OCCUPY → BIND
pub const ossify = affinity;     // OSSIFY → AFFINITY
pub const bond = tunnel;         // BOND → TUNNEL
pub const still = suspend_tool;       // STILL → SUSPEND
pub const quench = reset_tool;   // QUENCH → RESET
pub const forge_tool = inject_tool; // FORGE → INJECT
pub const void_tool = wipe;      // VOID → WIPE
pub const fossilize = persist;   // FOSSILIZE → PERSIST
pub const molt = snap;           // MOLT → SNAP
pub const veil = claim;          // VEIL → CLAIM (STEALTH flag)
pub const resonate = coordinate; // RESONATE → COORDINATE
pub const oscillate = coordinate;// OSCILLATE → COORDINATE
