/*
 * vitriol_alka.h — Alka/VITRIOL IOCTL Interface
 *
 * This header defines the binary protocol between the Alka compiler
 * and the VITRIOL kernel module. AlkaSol (.alkas) packets are sent
 * via ioctl() calls to /dev/vitriol.
 *
 * Generated by Alka Officina v3.0
 */

#ifndef VITRIOL_ALKA_H
#define VITRIOL_ALKA_H

#include <linux/ioctl.h>
#include <linux/types.h>

#define VITRIOL_DEVICE_NAME "vitriol"
#define VITRIOL_DEVICE_PATH "/dev/vitriol"

/* ============================================================================
 * Alka Drop Format (32 bytes)
 * ============================================================================ */

#define DROP_SIZE 32

struct alka_drop {
    __u8    op_code;        /* Instruction identifier */
    __u8    flags;          /* Execution flags (bit 7 = Azoth rollback) */
    __u16   vessel_id;      /* Target vessel index */
    __u64   src_addr;       /* Physical source address */
    __u64   dst_addr;       /* Physical destination address */
    __u32   size;           /* Transfer size in bytes */
    __u32   reserved;       /* Alignment padding */
    __u32   crc;            /* Integrity check (computed over bytes 0-27) */
} __attribute__((packed));

/* ============================================================================
 * Extended Alka Drop Format (64 bytes)
 * ============================================================================ */

#define DROP_SIZE_EXT 64

struct alka_drop_ext {
    __u8    op_code;        /* Instruction identifier */
    __u8    intensity;      /* Operation intensity */
    __u16   safety;         /* Safety level override */
    __u64   src_addr;       /* Physical source address */
    __u64   dst_addr;       /* Physical destination address */
    __u64   length;         /* Transfer length */
    __u8    pattern[32];    /* Operation pattern/data */
    __u32   auth_sig;       /* Authentication signature */
    __u32   reserved;       /* Padding */
} __attribute__((packed));

/* ============================================================================
 * Azoth Rollback Packet (32 bytes, flags bit 7 set)
 * ============================================================================ */

#define FLAG_AZOTH          0x80  /* Bit 7: This is a rollback packet */
#define FLAG_DRY_RUN        0x40  /* Bit 6: Simulate only */
#define FLAG_FORCE          0x20  /* Bit 5: Override safety checks */
#define FLAG_ASYNC          0x10  /* Bit 4: Async execution */
#define FLAG_BARRIER        0x08  /* Bit 3: Memory barrier after */
#define FLAG_THERMAL_CHECK  0x04  /* Bit 2: Pre-execution thermal check */

/* ============================================================================
 * Vial (Substrate) Description
 * ============================================================================ */

#define MAX_VESSELS         16
#define MAX_APERTURES       8
#define MAX_NAME_LEN        64

struct aperture_desc {
    __u8    bar;            /* PCI BAR number (0-5) */
    __u64   physical_base;  /* Physical base address */
    __u64   size;           /* Aperture size in bytes */
    __u64   max_window;     /* Maximum sliding window */
    __u8    is_prefetchable;
    __u8    requires_sliding_window;
    char    name[MAX_NAME_LEN];
};

struct thermal_desc {
    __u32   halt_at;        /* Temperature (milli-Celsius) */
    __u32   throttle_at;    /* Temperature (milli-Celsius) */
    char    sensor_path[MAX_NAME_LEN];
};

struct vessel_desc {
    __u16   vendor_id;
    __u16   device_id;
    __u8    bus;
    __u8    slot;
    __u8    function;
    __u8    aperture_count;
    char    name[MAX_NAME_LEN];
    struct aperture_desc apertures[MAX_APERTURES];
    struct thermal_desc thermal;
    __u8    dma_capable;
    __u8    isolated;
};

struct vial_desc {
    __u32   vessel_count;
    struct vessel_desc vessels[MAX_VESSELS];
};

/* ============================================================================
 * Execution Result
 * ============================================================================ */

#define EXEC_STATUS_OK      0
#define EXEC_STATUS_ERROR   1
#define EXEC_STATUS_THERMAL 2
#define EXEC_STATUS_TIMEOUT 3
#define EXEC_STATUS_CRC_FAIL 4

struct exec_result {
    __u32   status;
    __u32   packets_executed;
    __u32   packets_total;
    __u64   cycles_spent;
    __u64   bytes_transferred;
    __u32   thermal_peak;     /* Peak temperature during execution */
    __u32   error_packet;     /* Index of failed packet (if any) */
    char    error_msg[256];
};

/* ============================================================================
 * IOCTL Commands
 * ============================================================================ */

#define VITRIOL_IOC_MAGIC     'V'

/* Load a Vial (substrate description) */
#define VITRIOL_IOC_LOAD_VIAL    _IOW(VITRIOL_IOC_MAGIC, 1, struct vial_desc)

/* Execute an AlkaSol binary (array of alka_drop) */
#define VITRIOL_IOC_EXECUTE      _IOWR(VITRIOL_IOC_MAGIC, 2, struct { \
    void __user *packets; \
    __u32 packet_count; \
    __u32 packet_size; \
    struct exec_result __user *result; \
})

/* Execute with Azoth rollback on failure */
#define VITRIOL_IOC_EXECUTE_SAFE _IOWR(VITRIOL_IOC_MAGIC, 3, struct { \
    void __user *packets; \
    __u32 packet_count; \
    __u32 packet_size; \
    void __user *azoth_packets; \
    __u32 azoth_count; \
    struct exec_result __user *result; \
})

/* Get current substrate state */
#define VITRIOL_IOC_GET_STATE    _IOR(VITRIOL_IOC_MAGIC, 4, struct exec_result)

/* Set safety level (0=none, 1=thermal, 2=full) */
#define VITRIOL_IOC_SET_SAFETY   _IOW(VITRIOL_IOC_MAGIC, 5, __u32)

/* Read thermal sensor */
#define VITRIOL_IOC_READ_THERMAL _IOR(VITRIOL_IOC_MAGIC, 6, __u32)

/* Map a BAR window */
#define VITRIOL_IOC_MAP_BAR      _IOW(VITRIOL_IOC_MAGIC, 7, struct { \
    __u8 vessel_id; \
    __u8 bar; \
    __u64 offset; \
    __u64 size; \
})

/* Unmap a BAR window */
#define VITRIOL_IOC_UNMAP_BAR    _IOW(VITRIOL_IOC_MAGIC, 8, struct { \
    __u8 vessel_id; \
    __u8 bar; \
})

/* Heartbeat (for KV260 dead-man's switch) */
#define VITRIOL_IOC_HEARTBEAT    _IO(VITRIOL_IOC_MAGIC, 9)

/* Query supported opcodes */
#define VITRIOL_IOC_QUERY_OPS    _IOR(VITRIOL_IOC_MAGIC, 10, __u64)

#define VITRIOL_IOC_MAXNR 10

/* ============================================================================
 * Op-Code Definitions (matches Alka instruction set)
 * ============================================================================ */

#define ALKA_OP_CLAIM         0x01
#define ALKA_OP_STAKE         0x02
#define ALKA_OP_FLOW          0x03
#define ALKA_OP_SHIFT         0x04
#define ALKA_OP_FENCE         0x05
#define ALKA_OP_SYNC          0x06
#define ALKA_OP_SENSE         0x07
#define ALKA_OP_PULSE         0x08
#define ALKA_OP_SIGNAL        0x09
#define ALKA_OP_YIELD         0x0A
#define ALKA_OP_RECAST        0x0B
#define ALKA_OP_SNAP          0x0C
#define ALKA_OP_REVERT        0x0D
#define ALKA_OP_LIMIT         0x0E
#define ALKA_OP_VEIL          0x0F
#define ALKA_OP_DELEGATE      0x10
#define ALKA_OP_RHYTHM        0x11
#define ALKA_OP_DISTILL       0x12
#define ALKA_OP_ENQUEUE       0x13
#define ALKA_OP_MOLT          0x14
#define ALKA_OP_VOUCH         0x15
#define ALKA_OP_PROBE_BUS     0x16
#define ALKA_OP_ECHO          0x17
#define ALKA_OP_STASIS        0x18
#define ALKA_OP_TRANSVERSE    0x19
#define ALKA_OP_SEARCH        0x1A
#define ALKA_OP_FOSSILIZE     0x1B
#define ALKA_OP_STRIKE        0x1C
#define ALKA_OP_QUENCH        0x1D
#define ALKA_OP_FORGE         0x1E
#define ALKA_OP_VOID          0x1F
#define ALKA_OP_ABDUCT        0x20
#define ALKA_OP_SNOOP         0x21
#define ALKA_OP_SCATTER       0x22
#define ALKA_OP_WHISPER       0x23
#define ALKA_OP_GHOST         0x24
#define ALKA_OP_HIJACK        0x25
#define ALKA_OP_DRIFT         0x26
#define ALKA_OP_CLONE         0x27
#define ALKA_OP_CRYSTALLIZE   0x28
#define ALKA_OP_OVERCLOCK     0x29
#define ALKA_OP_FLUX          0x2A
#define ALKA_OP_AUDIT         0x2B
#define ALKA_OP_DRY_RUN       0x2C
#define ALKA_OP_MOCK          0x2D
#define ALKA_OP_PROVE         0x2E
#define ALKA_OP_WATCH         0x2F
#define ALKA_OP_TRACE         0x30
#define ALKA_OP_GUARD         0x31
#define ALKA_OP_ISOLATE       0x32
#define ALKA_OP_VERIFY        0x33
#define ALKA_OP_OSSIFY        0x34
#define ALKA_OP_BOND          0x35
#define ALKA_OP_STILL         0x36
#define ALKA_OP_RESONATE      0x37
#define ALKA_OP_OSCILLATE     0x38
#define ALKA_OP_IMC_HIJACK    0x39
#define ALKA_OP_OCCUPY        0x3A
#define ALKA_OP_REFRACT       0x3B
#define ALKA_OP_PIPE          0x3C

#endif /* VITRIOL_ALKA_H */
